version: "3"

tasks:
  # task generate-auth
  generate-auth:
    aliases:
      - gen
    desc: "Generate code for auth from proto file"
    cmds:
      - protoc -I proto proto/auth.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative