version: "3"

tasks:
  # task generate-auth
  generate-auth:
    aliases:
      - gen
    desc: "Generate code for auth from proto file"
    cmds:
      - protoc -I proto proto/auth/auth.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  generate-auth-with-gateway:
    desc: "Generate code for auth with gateway from proto file"
    cmds:
      - protoc -I proto proto/auth/auth.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative --grpc-gateway_out=./gen/go/ --grpc-gateway_opt=paths=source_relative
  
  generate-deployment:
    desc: "Generate code for deployment from proto file"
    cmds:
      - protoc -I proto proto/deployment/deployment.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative