version: "3"

tasks:
  generate-auth:
    desc: "Generate code for auth from proto file"
    cmds:
      - protoc -I proto proto/auth/auth.proto
        --go_out=./gen/go/
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/
        --go-grpc_opt=paths=source_relative 
        --grpc-gateway_out=./gen/go/
        --grpc-gateway_opt=paths=source_relative 
        --openapiv2_out=./gen/openapiv2/
        --openapiv2_opt=logtostderr=true

  generate-auth-nest:
    desc: "Generate code for auth from proto file"
    cmds:
      - protoc -I proto proto/auth/auth.proto 
        --plugin=./node_modules/.bin/protoc-gen-ts_proto
        --ts_proto_out=./gen/ts/
        --ts_proto_opt=nestJs=true

  generate-deployment:
    desc: "Generate code for deployment from proto file"
    cmds:
      - protoc -I proto proto/deployment/deployment.proto
        --go_out=./gen/go/
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/
        --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=./gen/go/
        --grpc-gateway_opt=paths=source_relative
        --openapiv2_out=./gen/openapiv2/
        --openapiv2_opt=logtostderr=true

  generate-deployment-nest:
    desc: "Generate code for deployment nest from proto file"
    cmds:
      - protoc -I proto proto/deployment/deployment.proto
        --plugin=./node_modules/.bin/protoc-gen-ts_proto
        --ts_proto_out=./gen/ts/
        --ts_proto_opt=nestJs=true

  generate-codegen-go:
    desc: "Generate golang code for codegen from proto file"
    cmds:
      - protoc -I proto proto/codegen/codegen.proto
        --go_out=./gen/go/
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/
        --go-grpc_opt=paths=source_relative

  generate-codegen-nest:
    desc: "Generate typescript code for codegen from proto file"
    cmds:
      - protoc -I proto proto/codegen/codegen.proto
        --plugin=./node_modules/.bin/protoc-gen-ts_proto
        --ts_proto_out=./gen/ts/
        --ts_proto_opt=nestJs=true

  generate-project-go:
    desc: "Generate golang code for project from proto file"
    cmds:
      - protoc -I proto proto/project/project.proto
        --go_out=./gen/go/
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/
        --go-grpc_opt=paths=source_relative

  generate-project-nest:
    desc: "Generate typescript code for project from proto file"
    cmds:
      - protoc -I proto proto/project/project.proto
        --plugin=./node_modules/.bin/protoc-gen-ts_proto
        --ts_proto_out=./gen/ts/
        --ts_proto_opt=nestJs=true